/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cad_is;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author Dell G5
 */
public class EditPanel extends javax.swing.JFrame {
    
    private String groupRadioSelection1;
    private String groupRadioSelection2;
    private int nid;
    private String ncato;
    private String nname;
    private String nrange;
    private Double nprice;
    private String nreco;
    

    /**
     * Creates new form EditPanel
     */
    public EditPanel(int id,String cato, String name, String range,Double price, String reco) {
        initComponents();
        this.nid = id;
        this.ncato = cato;
        this.nname = name;
        this.nrange = range;
        this.nprice = price;
        this.nreco = reco;
        groupRadioSelection1="";
        groupRadioSelection2="";
        this.setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        cato = new javax.swing.JComboBox();
        id = new javax.swing.JTextField();
        bg1 = new javax.swing.JRadioButton();
        bg2 = new javax.swing.JRadioButton();
        bg3 = new javax.swing.JRadioButton();
        name = new javax.swing.JTextField();
        bg4 = new javax.swing.JRadioButton();
        bg5 = new javax.swing.JRadioButton();
        bg6 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        kGradientPanel2.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkEndColor(new java.awt.Color(51, 51, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 255));
        kGradientPanel2.setOpaque(false);
        kGradientPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UPDATE THE SELECTED ACCESSORY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        kGradientPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Accessory_ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 170, 0, 0);
        kGradientPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 170, 0, 0);
        kGradientPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Accessory Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 170, 0, 0);
        kGradientPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Range");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 170, 0, 0);
        kGradientPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 170, 0, 0);
        kGradientPanel2.add(jLabel7, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Recomended By");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 170, 0, 0);
        kGradientPanel2.add(jLabel15, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_50px_1.png"))); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 120, 11, 0);
        kGradientPanel2.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_50px.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(null);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 76;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 7, 11, 88);
        kGradientPanel2.add(jButton2, gridBagConstraints);

        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 208;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 27, 0, 0);
        kGradientPanel2.add(price, gridBagConstraints);

        cato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Category>", "Media", "Comfort", "Decorative", "Cleaning", "Oils & Lubricants", "Others" }));
        cato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 33, 0, 0);
        kGradientPanel2.add(cato, gridBagConstraints);

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 36;
        gridBagConstraints.ipadx = 208;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 33, 0, 0);
        kGradientPanel2.add(id, gridBagConstraints);

        buttonGroup1.add(bg1);
        bg1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bg1.setForeground(new java.awt.Color(255, 255, 255));
        bg1.setText("High");
        bg1.setFocusable(false);
        bg1.setOpaque(false);
        bg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 3, 0, 0);
        kGradientPanel2.add(bg1, gridBagConstraints);

        buttonGroup1.add(bg2);
        bg2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bg2.setForeground(new java.awt.Color(255, 255, 255));
        bg2.setText("Medium");
        bg2.setFocusable(false);
        bg2.setOpaque(false);
        bg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 13, 0, 0);
        kGradientPanel2.add(bg2, gridBagConstraints);

        buttonGroup1.add(bg3);
        bg3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bg3.setForeground(new java.awt.Color(255, 255, 255));
        bg3.setText("Low");
        bg3.setFocusable(false);
        bg3.setOpaque(false);
        bg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 20, 0, 0);
        kGradientPanel2.add(bg3, gridBagConstraints);

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 212;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 23, 0, 0);
        kGradientPanel2.add(name, gridBagConstraints);

        buttonGroup2.add(bg4);
        bg4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bg4.setForeground(new java.awt.Color(255, 255, 255));
        bg4.setText("Not Recommended Yet");
        bg4.setFocusable(false);
        bg4.setOpaque(false);
        bg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 48;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
        kGradientPanel2.add(bg4, gridBagConstraints);

        buttonGroup2.add(bg5);
        bg5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bg5.setForeground(new java.awt.Color(255, 255, 255));
        bg5.setText("Recommended By Company");
        bg5.setFocusable(false);
        bg5.setOpaque(false);
        bg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 75;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 3, 0, 0);
        kGradientPanel2.add(bg5, gridBagConstraints);

        buttonGroup2.add(bg6);
        bg6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bg6.setForeground(new java.awt.Color(255, 255, 255));
        bg6.setText("Recommended By Community/Users");
        bg6.setFocusable(false);
        bg6.setOpaque(false);
        bg6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
        kGradientPanel2.add(bg6, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(0, 51, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_bin_50px.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.setBorder(null);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 23, 11, 0);
        kGradientPanel2.add(jButton3, gridBagConstraints);

        getContentPane().add(kGradientPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        First_Interface f = new First_Interface();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you Sure you want to Update the selected Item?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
          // Saving code here
           int ID=0;
        boolean found = false;    //  Specifies if the Accessory Id already Exists or not!!
        boolean exception = false;  // Specifies if the Input to the System is Correct or not/// Exception!!
        if (id.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID of Accessory Cannot be left Empty");
            exception=true; // True as ID is left Empty
        }else{
            try{
                ID= Integer.parseInt(id.getText());
            }catch(Exception NumberFormatException){
                JOptionPane.showMessageDialog(null, "ID of Accessory cannot be a String Value");
                exception=true; // True as Id is a String value
            }
        }
        if (exception==false){  
            for(int i = 0;i<f.model().getRowCount();i++){

                int oldID = Integer.parseInt(f.model().getValueAt(i, 0).toString());
                if(ID==oldID && ID!=nid){
                    found=true;

                }

            }
             if (found==false){  //Trigered if the id of data already stored, does not match input id of Accessory.
                this.UpdateDataToDataFile(ID, "..\\DataFile//CAD_IS.xls");

            }else{
                JOptionPane.showMessageDialog(null, "ID :"+ID+" already Exits \n Please choose another ID.");
            }
    
        }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.clearData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg1ActionPerformed
        // TODO add your handling code here:
        this.groupRadioSelection1 = "High";
        this.buttonGroup1.setSelected(bg1.getModel(), true);
    }//GEN-LAST:event_bg1ActionPerformed

    private void bg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg2ActionPerformed
        // TODO add your handling code here:
        this.groupRadioSelection1 = "Medium";
        this.buttonGroup1.setSelected(bg2.getModel(), true);
    }//GEN-LAST:event_bg2ActionPerformed

    private void bg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg3ActionPerformed
        // TODO add your handling code here:
        this.groupRadioSelection1 = "Low";
        this.buttonGroup1.setSelected(bg3.getModel(), true);
    }//GEN-LAST:event_bg3ActionPerformed

    private void bg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg4ActionPerformed
        // TODO add your handling code here:
        this.groupRadioSelection2 = "Not Recommended Yet";
    }//GEN-LAST:event_bg4ActionPerformed

    private void bg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg5ActionPerformed
        // TODO add your handling code here:
        this.groupRadioSelection2 = "Recommended By Company";
    }//GEN-LAST:event_bg5ActionPerformed

    private void bg6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg6ActionPerformed
        // TODO add your handling code here:
        this.groupRadioSelection2 = "Recommended By Community/Users";
    }//GEN-LAST:event_bg6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Delete Row Here
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you Sure you want to delete the selected Item?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
          // Saving code here
            this.DeleteSelectedRow("..\\DataFile//CAD_IS.xls");
        }
        //this.DeleteSelectedRow("..\\DataFile//CAD_IS.xls");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void catoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catoActionPerformed
    public void UpdateDataToDataFile(int ID,String path){
        try{
                String catogory = cato.getSelectedItem().toString();
                String AC_name = name.getText();
                String Ac_range = this.groupRadioSelection1.toString();      
                String Ac_reco = this.groupRadioSelection2.toString();

                if (name.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Accessory Name cannot be left Empty.");
                }else if(Ac_range ==""){
                    JOptionPane.showMessageDialog(null, "Range of Accessory is not Chosen");
                }else if(Ac_reco ==""){
                    JOptionPane.showMessageDialog(null, "Recomendation of Accessory is not Chosen");
                }else if(catogory.contains("<Select Category>")){
                JOptionPane.showMessageDialog(null, "Please Select Category");
                }else{


                    Double Ac_price = Double.parseDouble(price.getText());

                    File file = new File(path);

                    if(!file.exists()){
                        this.UpdateDataToDataFile(ID, "DataFile//CAD_IS.xls");

                    }else{
                        this.inserData(ID, catogory, AC_name, Ac_range, Ac_price, Ac_reco, path);
                    }
                }

            }catch(Exception NumberFormatException){

                JOptionPane.showMessageDialog(null, "Price cannot hold a String Value");

            }
    }
    public void inserData(int id,String cato, String name, String range,Double price, String reco, String path) throws BiffException{
       
        try {
                
                Workbook wb = Workbook.getWorkbook(new File(path));
                
                WritableWorkbook myexcel = Workbook.createWorkbook(new File(path),wb);
                
                WritableSheet mysheet = myexcel.getSheet(0);
                
                
                System.out.println();
                //Cell c = mysheet.getCell(0, 1).getContents();
                int row = mysheet.getRows();
                for (int i = 1;i< mysheet.getRows(); i++){
                    if (Integer.parseInt(mysheet.getCell(0, i).getContents())==nid){
                        row = i;
                        //JOptionPane.showMessageDialog(null, Integer.parseInt(mysheet.getCell(0, i).getContents()));
                        break;
                    }
                }
                
                
                    Label l1 = new Label(0,row,String.valueOf(id));
                    Label l2 = new Label(1,row,cato);
                    Label l3 = new Label(2,row,name);
                    Label l4 = new Label(3,row,range);
                    Label l5 = new Label(4,row,String.valueOf(price));
                    Label l6 = new Label(5,row,reco);
                    mysheet.addCell(l1);
                    mysheet.addCell(l2);
                    mysheet.addCell(l3);
                    mysheet.addCell(l4);
                    mysheet.addCell(l5);
                    mysheet.addCell(l6);

                    myexcel.write();
                    myexcel.close();
                    this.clearData();
                    
                    
                
                JOptionPane.showMessageDialog(null, " Data Updated Successfully!!");
                this.dispose();
                } catch (IOException ex) {
                    this.UpdateDataToDataFile(id, "DataFile//CAD_ID.xls");
                    //Logger.getLogger(First_Interface.class.getName()).log(Level.SEVERE, null, ex);
                } catch (WriteException ex) {
                    Logger.getLogger(First_Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
       
    }
    public void DeleteSelectedRow(String path){
                Workbook wb;
        try {
                wb = Workbook.getWorkbook(new File(path));
                
                WritableWorkbook myexcel = Workbook.createWorkbook(new File(path),wb);
                
                WritableSheet mysheet = myexcel.getSheet(0);
                
                
                System.out.println();
                //Cell c = mysheet.getCell(0, 1).getContents();
                int row = mysheet.getRows();
                for (int i = 1;i< mysheet.getRows(); i++){
                    if (Integer.parseInt(mysheet.getCell(0, i).getContents())==nid){
                        row = i;
                        //JOptionPane.showMessageDialog(null, Integer.parseInt(mysheet.getCell(0, i).getContents()));
                        break;
                    }
                }
                
                try {
                    mysheet.removeRow(row);
                    myexcel.write();
                    myexcel.close();
                    JOptionPane.showMessageDialog(null, "Data Deleted Successfully!!");
                    this.dispose();
                } catch (WriteException ex) {
                    Logger.getLogger(EditPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
        } catch (IOException ex) {
            this.DeleteSelectedRow("DataFile//CAD_IS.xls"); //Tries for another path if the file not found at privious path
        } catch (BiffException ex) {
            Logger.getLogger(EditPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void setData(){
         /* 
            It simply takes the selected data accessory from global 
            variable and sets into the text fields, combo box, and radio buttons used in the Edit sections.
        
        */
        this.id.setText(""+nid);
        this.cato.setSelectedItem(ncato);
        this.name.setText(nname);
        this.price.setText(""+nprice);
        
        
        if (bg1.getText().equals(this.nrange)){ //Condition For radioButtons(Range)
            this.buttonGroup1.setSelected(bg1.getModel(), true); //selects High
            this.groupRadioSelection1 = "High";
            
        }else if (bg2.getText().equals(this.nrange)){
            this.buttonGroup1.setSelected(bg2.getModel(), true); //selects medium
            this.groupRadioSelection1 = "Medium";
            
        }else if (bg3.getText().equals(this.nrange)){
            this.buttonGroup1.setSelected(bg3.getModel(), true); //Selectes Low
            this.groupRadioSelection1 = "Low";
        }
        
        if (bg4.getText().equals(nreco)){ //Condition For radioButtons(Recomendations)
            
            this.buttonGroup2.setSelected(bg4.getModel(), true); //selects "Not Recommended Yet"
            this.groupRadioSelection2 = "Not Recommended Yet";  
            
        }else if (bg5.getText().equals(nreco)){
            this.buttonGroup2.setSelected(bg5.getModel(), true); //selects "Recommended By Company"
            this.groupRadioSelection2 = "Recommended By Company";
            
        }else if (bg6.getText().equals(nreco)){
            this.buttonGroup2.setSelected(bg6.getModel(), true); //selects "Recommended By Community/Users"
            this.groupRadioSelection2 = "Recommended By Community/Users";
        }
        
    }
    public void clearData(){
        this.id.setText("");
        this.cato.setSelectedIndex(0);
        this.name.setText("");

        this.price.setText("");
        this.buttonGroup1.clearSelection();
        this.buttonGroup2.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bg1;
    private javax.swing.JRadioButton bg2;
    private javax.swing.JRadioButton bg3;
    private javax.swing.JRadioButton bg4;
    private javax.swing.JRadioButton bg5;
    private javax.swing.JRadioButton bg6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cato;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
